apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.30.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: minio
  name: minio
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: minio
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.30.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.network/mms-default: "true"
        io.kompose.service: minio
    spec:
      containers:
        - args:
            - server
            - /tmp/data
          env:
            - name: MINIO_ACCESS_KEY
              value: admintest
            - name: MINIO_SECRET_KEY
              value: admintest
          image: minio/minio:RELEASE.2022-05-26T05-48-41Z.hotfix.15f13935a
          name: minio
          ports:
            - containerPort: 9000
              hostPort: 9000
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
