---
apiVersion: v1
kind: "DeploymentConfig"
metadata:
  name: "openmbee-mms"
  annotations:
    description: "Handles deployment of the openmbee mms web api"
spec:
  strategy:
    resources:
      limits:
        cpu: 350m
        memory: 500Mi
      requests:
        cpu: 350m
        memory: 100Mi
    type: "Recreate"
  replicas: 1
  template:
    metadata:
      labels:
        name: "openmbee"
    spec:
      containers:
        - env:
            - name: ASPNETCORE_URLS
              value: http://*:5000
          name: "openmbee-mms"
          image: "registry-cli-docker.wseasttest.navair.navy.mil:5000/722sysdev/openmbee-mms:latest"
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/Health/healthz
              port: 5000
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 38
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/v1/Health/healthz
              port: 5000
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 30
          volumeMounts:
            - name: appsettings-config
              mountPath: /app/appsettings.json
              subPath: appsettings.json
          ports:
            - containerPort: 5000
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1G
            requests:
              cpu: 350m
              memory: 500M
      volumes:
        - name: appsettings-config
          secret:
            secretName: appsettings-config
            items:
              - key: appsettings.json
                path: appsettings.json
  triggers: []
