---
apimmsrsion: v1
kind: "BuildConfig"
metadata:
  name: "openmbee-mms-pipeline"
spec:
  completionDeadlineSeconds: 1800
  source:
    git:
      ref: "master"
      uri: ""
    contextDir: "openmbee"
    sourceSecret:
      name: "tfs-pull-secret"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
