---
apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    template.alpha.openshift.io/wait-for-ready: 'true'
  name: postgres
spec:
  replicas: 1
  selector:
    name: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: postgres
    spec:
      containers:
        - env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: database-password
                  name: "postgres"
          image: ""
          imagePullPolicy: Always
          name: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: "/var/opt/postgres"
              name: "postgres-data"
      volumes:
        - name: "postgres-data"
          persistentVolumeClaim:
            claimName: "postgres"
