---
apiVersion: v1
kind: "Service"
metadata:
  name: "openmbee-mms"
  annotations:
    description: "Exposes and load balances the application pods"
spec:
  ports:
    - name: "openmbee-mms-port"
      port: 5000
      targetPort: 5000
  selector:
    name: "openmbee"
